test_demo_numeric1type (__main__.Test_demoString) ... ERROR
test_demo_numeric2type (__main__.Test_demoString) ... ERROR
test_demo_numeric3type (__main__.Test_demoString) ... ERROR
test_demo_string1type (__main__.Test_demoString) ... ERROR

======================================================================
ERROR: test_demo_numeric1type (__main__.Test_demoString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/NumericDataTypeTest.py", line 23, in test_demo_numeric1type
    actual = self.data_type_usage.demo_numeric1type(100)
AttributeError: Data_Type_Usage instance has no attribute 'demo_numeric1type'

======================================================================
ERROR: test_demo_numeric2type (__main__.Test_demoString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/NumericDataTypeTest.py", line 29, in test_demo_numeric2type
    actual = self.data_type_usage.demo_numeric2type(34.45)
AttributeError: Data_Type_Usage instance has no attribute 'demo_numeric2type'

======================================================================
ERROR: test_demo_numeric3type (__main__.Test_demoString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/NumericDataTypeTest.py", line 35, in test_demo_numeric3type
    actual = self.data_type_usage.demo_numeric3type(3 + 4j)
AttributeError: Data_Type_Usage instance has no attribute 'demo_numeric3type'

======================================================================
ERROR: test_demo_string1type (__main__.Test_demoString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/NumericDataTypeTest.py", line 17, in test_demo_string1type
    actual = self.data_type_usage.demo_string1type("beginnersbook")
AttributeError: Data_Type_Usage instance has no attribute 'demo_string1type'

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (errors=4)
