test_Add (__main__.SumTest) ... ERROR
test_get_set (__main__.SumTest) ... ERROR
test_get_size (__main__.SumTest) ... ERROR

======================================================================
ERROR: test_Add (__main__.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/SetDataTypeTest.py", line 15, in test_Add
    self.set.Add("Google")
AttributeError: Set instance has no attribute 'Add'

======================================================================
ERROR: test_get_set (__main__.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/SetDataTypeTest.py", line 21, in test_get_set
    self.set = Set({'orange', 'apple', 'pear', 'banana'})
TypeError: this constructor takes no arguments

======================================================================
ERROR: test_get_size (__main__.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/SetDataTypeTest.py", line 27, in test_get_size
    self.set = Set({1.0, "Hello", (1, 2, 3)})
TypeError: this constructor takes no arguments

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)
