test_demo_condition (__main__.Test_demoCondition) ... ERROR
test_demo_condition1 (__main__.Test_demoCondition) ... ERROR
test_demo_condition2 (__main__.Test_demoCondition) ... ERROR

======================================================================
ERROR: test_demo_condition (__main__.Test_demoCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/ifelseTest.py", line 15, in test_demo_condition
    actual = self.condition.demo_Condition(9)
AttributeError: Condition instance has no attribute 'demo_Condition'

======================================================================
ERROR: test_demo_condition1 (__main__.Test_demoCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/ifelseTest.py", line 20, in test_demo_condition1
    actual = self.condition.demo_Condition1(-9)
AttributeError: Condition instance has no attribute 'demo_Condition1'

======================================================================
ERROR: test_demo_condition2 (__main__.Test_demoCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/ifelseTest.py", line 25, in test_demo_condition2
    actual = self.condition.demo_Condition2(0)
AttributeError: Condition instance has no attribute 'demo_Condition2'

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)
